### 넘파이(Numpy) : 배열(ndarray, n dimension array)
#### 리스트(list): Linked List 구조(불연속), 동작 속도가 느리다, comma로 요소 구별, 서로 다른 자료형 사용가능
#### 배열(ndarray) : 연속된 메모리 구조, 동작 속도가 빠르다, comma를 사용하지 않고 공백으로 요소를 구별, 오직 한 가지 타입만 갖을 수 있다

In [18]:
import numpy as np
# pip install numpy

# list
list1 = [0,1,2,3,4,5,'hello']
print(list1,type(list1))

# ndarray
a = np.array([0,1,2,3,4,5])
print(a,type(a))            # <class 'numpy.ndarray'>
print(a.dtype)              # 요소의 자료형 int32(windows) , int64(Mac/Linux)
a     # Shift + Tab : 변수위에 커서를 놓고 함수(메서드)의 프로토 타입을 볼수 있다

[0, 1, 2, 3, 4, 5, 'hello'] <class 'list'>
[0. 1. 2. 3. 4. 5.] <class 'numpy.ndarray'>
float64


array([0., 1., 2., 3., 4., 5.])

In [17]:
# numpy 의 dtype 객체의 종류 : 대소문자 모두 사용 가능
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [23]:
# int와 float --> float
a = np.array([0,1,2.,3,4,5])
print(a,a.dtype) # 요소의 자료형: float64

[0.  1.  2.5 3.  4.  5. ] float64


In [46]:
# int와 float와 str --> Unicode string
a = np.array([0,1,2.,3,4,5,'Hello'])
print(a,a.dtype) # <U32    , < : 리틀엔디언 , U:유니코드 , 32: 최대 문자 32byte

# 유니코드 인코딩 방식
# (1) EUC-KR,CP949(MS949) : 완성형, 한글 2 바이트, 영문은 1 바이트, Windows
# (2) UTF-8 : 조합형, 한글 3 바이트, 영문은 1 바이트, Linux/Mac

['0' '1' '2.0' '3' '4' '5' 'Hello'] <U32


In [45]:
# 배열의 데이터 타입 변환 : astype()
a1 = np.array(['1.234','3.123','4.4356','5','7'])
print(a1,a1.dtype)  # 요소의 자료형 : <U6

a2 = a1.astype('float32')
print(a2,a2.dtype)  # 요소의 자료형: float32

a3 = a2.astype('int32')
print(a3,a3.dtype)  # float32

# a3 = a1.astype('int32')  # ValueError

['1.234' '3.123' '4.4356' '5' '7'] <U6
[1.234  3.123  4.4356 5.     7.    ] float32
[1 3 4 5 7] int32


### 차원(Dimension,Rank) 과 Shape
#### * 차원(Dimension,Rank)  : 1,2,3차원,n차원, 첫 데이터까지의 대괄호의 갯수
#### * Shape : 차원의 요소의 수, 튜플 형식
####  1 차원 Shape : (x,)
####  2 차원 Shape : (x,y), 행렬(matrix)
####  3 차원 Shape : (x,y,z) , (면,행,열) 
... 
####  n 차원 Shape : (x,y,z,....)

In [56]:
# 1차원 배열의 shape
# arange(start,end+1,step)
a = np.arange(12)
print(a,type(a),a.ndim,a.shape)  # 1차원  (12,)
t = a.shape
print(type(t))
print(a.shape[0])  # 12

a2 = np.arange(2,10)
print(a2,a2.shape) # (8,)

a3 = np.arange(0,16,2)
print(a3,a3.shape) # (8,)

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'> 1 (12,)
<class 'tuple'>
12
[2 3 4 5 6 7 8 9] (8,)
[ 0  2  4  6  8 10 12 14] (8,)


In [64]:
# 2차원 배열의 Shape : 행(row,가로,수직,axis=0)과 열(column,세로,수평,axis=1) => 필수암기 
# m = np.array([np.arange(3),np.arange(3)])
m = np.array([[0,1,2],
              [0,1,2]])
print(m,m.shape)   # (2,3)

m = np.array([[0,1],
              [3,4],
              [6,7]])
print(m,m.shape)   # (3,2)
print(m.shape[0],m.shape[1])

[[0 1 2]
 [0 1 2]] (2, 3)
[[0 1]
 [3 4]
 [6 7]] (3, 2)
3 2


In [69]:
# 3 차원 배열의 Shape: (면,행,열)
m = np.array([[[0,1,2],
               [3,4,5]],
              [[0,1,2],
               [3,4,5]]])
print(m,m.shape)   # (2,2,3)

m = np.array([[[0, 1],
               [2, 3]],
              [[4, 5],
               [0, 1]],
              [[2, 3],
               [4, 5]]])
print(m,m.shape)   # (3,2,2)

m = np.array([[[0, 1, 2]],
              [[3, 4, 5]],
              [[0, 1, 2]],
              [[3, 4, 5]]])
print(m,m.shape)   # (4,1,3)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]] (2, 2, 3)
[[[0 1]
  [2 3]]

 [[4 5]
  [0 1]]

 [[2 3]
  [4 5]]] (3, 2, 2)
[[[0 1 2]]

 [[3 4 5]]

 [[0 1 2]]

 [[3 4 5]]] (4, 1, 3)


### 배열의 shape 바꾸기 : reshape() 함수

In [89]:
m1 = np.arange(12)
print(m1,m1.shape) # (12,)

m2 = m1.reshape(12,1)
print(m2,m2.shape) # (12, 1)

m2 = m1.reshape(3,4)
print(m2,m2.shape) # (3,4)

m2 = m1.reshape(2,6)
print(m2,m2.shape) # (2,6)

m3 = m1.reshape(2,2,3)
print(m3,m3.shape) # (2,2,3)

m4 = m1.reshape(3,2,1,2)
print(m4,m4.shape) # (3,2,1,2)

m = np.arange(18).reshape(3,6)
print(m,m.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] (12, 1)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
[[[[ 0  1]]

  [[ 2  3]]]


 [[[ 4  5]]

  [[ 6  7]]]


 [[[ 8  9]]

  [[10 11]]]] (3, 2, 1, 2)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] (3, 6)


In [100]:
# -1을 사용한 reshape
m1 = np.arange(12)
print(m1,m1.shape)    #  (12,)

m2 = m1.reshape(-1,6) # 행의 요소수를 자동으로 계산, 2
print(m2,m2.shape)    # (2,6)

m2 = m1.reshape(4,-1) # 열의 요소수를 자동으로 계산, 3
print(m2,m2.shape)    # (4,3)

# m2 = m1.reshape(-1,-1) # ValueError

m2 = m1.reshape(-1,1) # 행의 요소수를 자동으로 계산, 12
print(m2,m2.shape)    # (12, 1)

m3 = m1.reshape(-1,2,2,1) # 면의 요소수를 자동으로 계산, 3
print(m3,m3.shape)    # (3,2,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] (12, 1)
[[[[ 0]
   [ 1]]

  [[ 2]
   [ 3]]]


 [[[ 4]
   [ 5]]

  [[ 6]
   [ 7]]]


 [[[ 8]
   [ 9]]

  [[10]
   [11]]]] (3, 2, 2, 1)


### 배열의 인덱싱과 슬라이싱

In [113]:
# 1차원 배열의 인덱싱과 슬라이싱 : list 와 동일한 방법
d = np.arange(12)
print(d,d.shape)

# indexing
print(d[0],d[1],d[2],d[-1],d[-2])

# slicing
print(d[2:8],d[:],d[:-1])
print(d[::2],d[::-1])

d[0] = 10   # list 처럼 요소 변경이 가능
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0 1 2 11 10
[2 3 4 5 6 7] [ 0  1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10] [11 10  9  8  7  6  5  4  3  2  1  0]
[10  1  2  3  4  5  6  7  8  9 10 11]


In [137]:
# 2차원 배열의 인덱싱과 슬라이싱 
# data[행,열]
d = np.arange(12).reshape(3,4)
print(d,d.shape)  # (3, 4)

# indexing
print(d[0][0])  # 0
print(d[0,0])   # 0
print(d[2,1])   # 9

# slicing
print(d[0])    # [0 1 2 3]
print(d[0,:])  # [0 1 2 3]
print(d[:,:-1])  # 마지막 열을 제외 ,(3,3)
print(d[::2,::2]) # (2,2)

d[0] = 20        # 0번 행의 모든 요소를 20으로 변경
print(d)

d[::2,::3] = 30  # 슬라이싱 된 요소 전체를 한번에 변경할 수 있다
print(d[::2,::3])
print(d)

d[:,:] = -1      # 전체 요소를 한번에 변경할 수 있다
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
0
0
9
[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]
[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[30 30]
 [30 30]]
[[30 20 20 30]
 [ 4  5  6  7]
 [30  9 10 30]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [164]:
# 3차원 배열의 인덱싱과 슬라이싱
# data[면,행,열]
d = np.arange(12).reshape(2,2,3)
print(d,d.shape)

# indexing
print(d[0][0][0])  # old style
print(d[0,0,0])    # 0
print(d[0,1,2])    # 5 

# slicing
print('-'*30)
print(d[:,:-1,:-1])  # (2, 1, 2)
print('-'*30)
print(d[:,1:,1:])    # (2, 1, 2)
print('-'*30)
print(d[:,:,-1])     # (2, 2)
print('-'*30)
print(d[:,-1,-1])    # (2,)

print(d[-1,-1,-1])    # 11, scalar

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)
0
0
5
------------------------------
[[[0 1]]

 [[6 7]]]
------------------------------
[[[ 4  5]]

 [[10 11]]]
------------------------------
[[ 2  5]
 [ 8 11]]
------------------------------
[ 5 11]
11


### 불린 인덱싱 : 조건식을 사용한 인덱싱, 조건 검색 필터를 사용한 추출(매우 중요)

In [186]:
a = np.array([1,2,3,4,5,6])
print(a)

print( a > 2)
print(a[a>2])
# print(a[[False, False, True, True, True, True]])

boolean_index = np.array([True,False,True,False,True,True])
print(boolean_index)
print(a[boolean_index])




[1 2 3 4 5 6]
[False False  True  True  True  True]
[3 4 5 6]
[ True False  True False  True  True]
[1 3 5 6]
